"""users table

Revision ID: 17f911c94023
Revises: 
Create Date: 2020-09-24 21:49:50.462154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f911c94023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fixed_capacity', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fixed_dedup', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fixed_dedup')
    op.drop_column('user', 'fixed_capacity')
    # ### end Alembic commands ###
